apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-info-service
spec:
  selector:
    matchLabels:
      app: travel-info-service
  template:
    metadata:
      labels:
        app: travel-info-service
    spec:
      containers:
      - name: travel-info-service
        image: europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-travel-info-service:0.2.12
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: tis-port
          containerPort: 8083
        env:
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: travel-info-secrets
              key: WEATHER_API_KEY
          
