apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: <Image>
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: JWT_EXPIRATION
        - name: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: GOOGLE_CLOUD_STORAGE_BUCKET
        - name: GOOGLE_CLOUD_CREDENTIALS_BASE64
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: GOOGLE_CLOUD_CREDENTIALS_BASE64
        - name: GOOGLE_CLOUD_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: cloudappdev-secrets
              key: GOOGLE_CLOUD_PROJECT_ID
