apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
spec:
  selector:
    matchLabels:
      app: social-service
  template:
    metadata:
      labels:
        app: social-service
    spec:
      serviceAccountName: cloudappdev-sa
      containers:
      - name: social-service
        image: europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-social-service:0.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
          name: social-port
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: NODE_ENV
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: MONGODB_URI
        - name: ITINERARY_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: ITINERARY_SERVICE_URL
        - name: USER_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: USER_SERVICE_URL
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: SENDGRID_API_KEY
        - name: SENDGRID_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: SENDGRID_FROM_EMAIL
        - name: NEWSLETTER_FROM_NAME
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: NEWSLETTER_FROM_NAME
        - name: NEWSLETTER_MODE
          valueFrom:
            secretKeyRef:
              name: social-service-secrets
              key: NEWSLETTER_MODE
        