apiVersion: v1
kind: Service
metadata:
  name: social-service
spec:
  selector:
    app: social-service
  ports:
  - protocol: TCP
    name: social-svc-port
    port: 8082
    targetPort: social-port
