apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "social.fullname" . }}
  labels:
    {{- include "social.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "social.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "social.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "social.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: social-port
              containerPort: {{ .Values.container.port }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
