apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: cloudappdev-sa
      initContainers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          restartPolicy: Always
          args:
            - "--port=5432"
            - "oceanic-citadel-474512-c1:europe-west1:cloudappdev-tf-users-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              # The proxy's memory use scales linearly with the number of active
              # connections. Fewer open connections will use less memory. Adjust
              # this value based on your application's requirements.
              memory: "2Gi"
              # The proxy's CPU use scales linearly with the amount of IO between
              # the database and the application. Adjust this value based on your
              # application's requirements.
              cpu: "1"

      containers:
      - name: user-service
        image: europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-user-service:0.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_EXPIRATION
        - name: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: GOOGLE_CLOUD_STORAGE_BUCKET
        - name: GOOGLE_CLOUD_CREDENTIALS_BASE64
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: GOOGLE_CLOUD_CREDENTIALS_BASE64
        - name: GOOGLE_CLOUD_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: GOOGLE_CLOUD_PROJECT_ID

