apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: cloudappdev-sa
      initContainers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          restartPolicy: Always
          args:
            - "--port=5432"
            - "oceanic-citadel-474512-c1:europe-west1:cloudappdev-tf-users-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      containers:
      - name: user-service
        image:   europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-user-service:0.2.24
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
          name: user-port
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: JWT_EXPIRATION
        - name: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
        - name: GOOGLE_CLOUD_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: GOOGLE_CLOUD_STORAGE_BUCKET
        - name: GOOGLE_CLOUD_CREDENTIALS_BASE64
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: GOOGLE_CLOUD_CREDENTIALS_BASE64
        - name: GOOGLE_CLOUD_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: user-service-secrets
              key: GOOGLE_CLOUD_PROJECT_ID

