apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudappdev-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudappdev-frontend
  template:
    metadata:
      labels:
        app: cloudappdev-frontend
    spec:
      serviceAccountName: cloudappdev-sa
      containers:
        - name: frontend
          image: europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-frontend@sha256:74ede7570c6ccb6c8b70a29c1102548f4a4a0c7ec338e8a5e8f580fbd22a255a
          ports:
            - containerPort: 3000
              name: frontend-port
          env:
            - name: NEXT_PUBLIC_API_GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  name: cloudappdev-secrets
                  key: API_GATEWAY_URL
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet: 
              path: "/"
              port: 3000
          readinessProbe:
            httpGet: 
              path: "/"
              port: 3000