apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudappdev-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account:
      "run-exec@oceanic-citadel-474512-c1.iam.gserviceaccount.com"