---
# Source: itinerary/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itinerary-service-sa
  labels:
    helm.sh/chart: itinerary-1.0.2
    app.kubernetes.io/name: itinerary
    app.kubernetes.io/instance: itinerary-service
    app.kubernetes.io/version: "0.2.29"
    app.kubernetes.io/managed-by: Helm
  annotations:
    iam.gke.io/gcp-service-account: run-exec@oceanic-citadel-474512-c1.iam.gserviceaccount.com
---
# Source: itinerary/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: itinerary-service
  labels:
    helm.sh/chart: itinerary-1.0.2
    app.kubernetes.io/name: itinerary
    app.kubernetes.io/instance: itinerary-service
    app.kubernetes.io/version: "0.2.29"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: itinerary
    app.kubernetes.io/instance: itinerary-service
---
# Source: itinerary/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itinerary-service
  labels:
    helm.sh/chart: itinerary-1.0.2
    app.kubernetes.io/name: itinerary
    app.kubernetes.io/instance: itinerary-service
    app.kubernetes.io/version: "0.2.29"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: itinerary
      app.kubernetes.io/instance: itinerary-service
  template:
    metadata:
      labels:
        helm.sh/chart: itinerary-1.0.2
        app.kubernetes.io/name: itinerary
        app.kubernetes.io/instance: itinerary-service
        app.kubernetes.io/version: "0.2.29"
        app.kubernetes.io/managed-by: Helm
    spec:
      initContainers:
        - args:
          - --port=5432
          - oceanic-citadel-474512-c1:europe-west1:cloudappdev-tf-itinerary-db
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
          name: cloud-sql-proxy
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          restartPolicy: Always
          securityContext:
            runAsNonRoot: true
      serviceAccountName: itinerary-service-sa
      containers:
        - name: itinerary
          image: "europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-itinerary-service:0.2.29"
          imagePullPolicy: IfNotPresent
          ports:
            - name: itinerary-port
              containerPort: 8081
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            tcpSocket:
              port: 8081
          readinessProbe:
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 1
            tcpSocket:
              port: 8081
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  key: NODE_ENV
                  name: itinerary-service-secrets
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: itinerary-service-secrets
            - name: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
              valueFrom:
                secretKeyRef:
                  key: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
                  name: itinerary-service-secrets
            - name: GOOGLE_CLOUD_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLOUD_STORAGE_BUCKET
                  name: itinerary-service-secrets
            - name: GOOGLE_CLOUD_CREDENTIALS_BASE64
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLOUD_CREDENTIALS_BASE64
                  name: itinerary-service-secrets
            - name: GOOGLE_CLOUD_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLOUD_PROJECT_ID
                  name: itinerary-service-secrets
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  key: FRONTEND_URL
                  name: itinerary-service-secrets
---
# Source: itinerary/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: itinerary-service
  labels:
    helm.sh/chart: itinerary-1.0.2
    app.kubernetes.io/name: itinerary
    app.kubernetes.io/instance: itinerary-service
    app.kubernetes.io/version: "0.2.29"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: itinerary-service
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: itinerary/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "itinerary-service-test-connection"
  labels:
    helm.sh/chart: itinerary-1.0.2
    app.kubernetes.io/name: itinerary
    app.kubernetes.io/instance: itinerary-service
    app.kubernetes.io/version: "0.2.29"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['itinerary-service:8081']
  restartPolicy: Never
