{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ "user-{{ $.Values.namespace }}-sa" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "user.labels" . | nindent 4 }}

  annotations:
    iam.gke.io/gcp-service-account: "user-{{ $.Values.namespace }}-sa@cloudappdev-dev.iam.gserviceaccount.com"
{{- end }}
