apiVersion: v1
kind: Service
metadata:
  name: infrastructure-provisioner-service
  labels:
    app: infrastructure-provisioner
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: infrastructure-provisioner
