apiVersion: v1
kind: Service
metadata:
  name: itinerary-service
  labels:
    app: itinerary-service
spec:
  selector:
    app: itinerary-service
  ports:
  - name: itinerary-svc-port
    port: 8081
    targetPort: itinerary-port