# Namespace where this chart will be deployed
namespace: default

image:
  repository: europe-west1-docker.pkg.dev/oceanic-citadel-474512-c1/docker-repo/cloudappdev-itinerary-service
  pullPolicy: IfNotPresent
  tag: ""

container:
  port: 8081
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

podLabels: {}

initContainers:
  - name: cloud-sql-proxy
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
    args:
      - "--port=5432"
      - "oceanic-citadel-474512-c1:europe-west1:cloudappdev-tf-itinerary-db"
    restartPolicy: Always
    securityContext:
      runAsNonRoot: true
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"

env:
  - name: NODE_ENV
    valueFrom:
      secretKeyRef:
        name: itinerary-service-secrets
        key: NODE_ENV
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        key: DATABASE_URL
        name: itinerary-service-secrets
  - name: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
    valueFrom:
      secretKeyRef:
        name: itinerary-service-secrets
        key: FIREBASE_SERVICE_ACCOUNT_JSON_BASE64
  - name: GOOGLE_CLOUD_STORAGE_BUCKET
    valueFrom:
      secretKeyRef:
        name: itinerary-service-secrets
        key: GOOGLE_CLOUD_STORAGE_BUCKET
  - name: GOOGLE_CLOUD_CREDENTIALS_BASE64
    valueFrom:
      secretKeyRef:
        name: itinerary-service-secrets
        key: GOOGLE_CLOUD_CREDENTIALS_BASE64
  - name: GOOGLE_CLOUD_PROJECT_ID
    valueFrom:
      secretKeyRef:
        name: itinerary-service-secrets
        key: GOOGLE_CLOUD_PROJECT_ID
  - name: FRONTEND_URL
    valueFrom: 
      secretKeyRef:
        key: FRONTEND_URL
        name: itinerary-service-secrets

serviceAccount:
  create: true
  annotations: 
    iam.gke.io/gcp-service-account: "run-exec@oceanic-citadel-474512-c1.iam.gserviceaccount.com"
  name: "itinerary-service-sa"

service:
  type: ClusterIP
  port: 8081

readinessProbe:
  tcpSocket:
    port: 8081
  initialDelaySeconds: 5
  failureThreshold: 30
  periodSeconds: 1
livenessProbe:
  tcpSocket:
    port: 8081
  initialDelaySeconds: 30
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

