apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "itinerary.fullname" . }}
  labels:
    {{- include "itinerary.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    {{- include "itinerary.selectorLabels" . | nindent 4 }}
