{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioning-default-sa
  annotations:
    iam.gke.io/gcp-service-account: provisioning-default-sa@cloudappdev-dev.iam.gserviceaccount.com
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
