{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "provisioning.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "provisioning.labels" . | nindent 4 }}

  annotations:
    iam.gke.io/gcp-service-account: "provisioning-{{ $.Values.namespace }}-sa@cloudappdev-dev.iam.gserviceaccount.com"
{{- end }}
